// Generated by https://quicktype.io

export interface Menu {
  main: MenuItem[];
}

export interface MenuItem {
  id: string;
  name: string;
  url: string;
  icon: string;
  locale: boolean;
  children?: MenuItem[];
}
