// Generated by https://quicktype.io

export interface PageHeaderNav {
  main: PageHeaderItem[];
  secondary: PageHeaderItem[];
}

export interface PageHeaderItem {
  id: string;
  name: string;
  url: string;
  icon: string;
}
